export const root = {
  baseUrl: process.env.NEXT_PUBLIC_BACKEND_URL,
};

export const endPoints = {
  register: "/account/register",
  login: "/account/login",
  getAccessToken: "/account/access-token",
  forgotPass: "/account/forgot-pass",
  resetPass: "/account/reset-pass",
  registerImage: "/account/register-image",
  checkApprovalStatus: "/account/check-approval-status",
  logout: "/account/logout",
  userDetailsMini: "/account/user-deatils-mini",
  resendVerifyEmail: "/account/resend-verify-email",
  updatePassword: "/account/password",
  verifyAccount: "/account/verify",
  updateMobile: "/account/mobile",
  updateEmail: "/account/email",
  exists: "/account/exists",

  static: "/static",

  getMatches: "/user/matches",
  getLikesList: "/user/likes-list",
  getUserDetails: "/user/profile",
  getPartnerPreferences: "/user/partner-preferences",
  getCurrentPlan: "/user/current-plan",
  addLiked: "/user/addliked",
  removeLiked: "/user/removeliked",
  updateProfile: "/user/profile",
  addImages: "/user/images",
  deleteImage: "/user/image",
  unlockProfile: "/user/unlock",
  getUnlockedProfiles: "/user/unlocked",

  getUsersList: "/admin/users",
  updateUserDetails: "/admin/user",
  getMarriedUsers: "/admin/users/married",
  marriedTo: "/admin/user/married-to",
  findUser: "/admin/user/find",
  extractImg: "/extractor",

  createOrder: "/payment/create-order",
  verifyPayment: "/payment/verify",
  testCreateOrder: "/payment/test-create-order",
  testVerifyPayment: "/payment/test-verify",

  getPaidUsers: "/super-admin/users/paid",
  getAssistedSubscribedUsers: "/super-admin/users/assisted-subscribed",
  getAllPayments: "/super-admin/users/all-payments",
  getUsersByCreatedBy: "/super-admin/users/created-by",
  getUsersGroupedByAdminCount: "/super-admin/users/grouped-by-admin/count",
  getUsersGroupedCount: "/super-admin/users/grouped/count",
  getUsersGroupedList: "/super-admin/users/grouped/list",
  getAdminsList: "/super-admin/admins",
  updateAdmin: "/super-admin/admin",
  getNotInvitedUsers: "/super-admin/users/not-invited",
  inviteUser: "/super-admin/user/invite",
  resetPassByAdmin: "/super-admin/user/password",
  makePaymentForUser: "/super-admin/user/payment",
}
